name: Deploy on Push

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd /home/opc/SnapQuest
            git pull origin main
            # If your bun path is /home/opc/.bun/bin/bun, use that exact path:
            /home/opc/.bun/bin/bun install
            # Reload systemd, just in case the service file changed:
            sudo systemctl daemon-reload
            # Restart the snapquest service to pick up new changes:
            sudo systemctl restart snapquest
